project:
  type: book
  output-dir: docs
  
date: '18 December 2025'
date-format: DD-MM-YYYY
date-modified: today
published-title: Created

book:
  title: "Special Areas for Bird Conservation"
  subtitle: 'KBAs and Protect Areas'
  # author: "Norah Jones"
  page-navigation: true
  repo-url: https://https://github.com/arbobm/special_areas/
  repo-actions: [edit]
  downloads: [pdf, docx]
  sharing: [linkedin]
  chapters:
    - index.qmd
    # - intro.qmd
    - countries_qmd/argentina.qmd
    - countries_qmd/philippines.qmd
    - countries_qmd/bangladesh.qmd
    - countries_qmd/cambodia.qmd
    - countries_qmd/ecuador.qmd
    # - countries_qmd/indonesia.qmd
    - countries_qmd/kazakhstan.qmd
    - countries_qmd/kyrgyzstan.qmd
    - countries_qmd/turkmenistan.qmd
    # - summary.qmd
    - references.qmd
  appendices:
    - news.qmd

bibliography: 
  - references.bib
  - wdpar.bib
number-sections: false
reference-location: margin
citation-location: margin
csl: templates/cambridge-journal-of-economics.csl

format:
  html:
    code-fold: true
    code-overflow: wrap
    theme:
      - cosmo
      - templates/styles.scss

execute: 
  warning: false
  error: false
  comments: false
  message: false
  
comments:
  giscus:
    repo: arbobm/special_areas


