project:
  type: book
  output-dir: docs

  
date: '18 December 2025'
date-format: DD-MM-YYYY
date-modified: today
published-title: Created

book:
  title: "Special Areas for Bird Conservation"
  subtitle: 'KBAs and Protect Areas'
  # author: "Norah Jones"
  page-navigation: true
  repo-url: https://github.com/arbobm/special_areas/
  chapters:
    - index.qmd
    # - intro.qmd
    - argentina.qmd
    - philippines.qmd
    - bangladesh.qmd
    - cambodia.qmd
    - ecuador.qmd
    # - indonesia.qmd
    - kazakhstan.qmd
    - kyrgyzstan.qmd
    - turkmenistan.qmd
    # - summary.qmd
    - references.qmd
  appendices:
    - news.qmd

bibliography: 
  - references.bib
  - wdpar.bib
number-sections: false
reference-location: margin
citation-location: margin
csl: templates/cambridge-journal-of-economics.csl

format:
  html:
    code-fold: true
    code-overflow: wrap
    theme:
      - cosmo
      - templates/styles.scss

execute: 
  warning: false
  error: false
  comments: false
  message: false
  
comments:
  giscus:
    repo: arbobm/special_areas


